import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#fffef8",
  },
  content: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 78,
    paddingHorizontal: 28,
    paddingTop: 28,
  },
  logoBlock: {
    alignItems: "center",
    marginTop: 24,
  },
  logoMy: {
    color: "#294832",
    fontSize: 56,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 62,
  },
  smoothieLine: {
    alignItems: "flex-start",
    flexDirection: "row",
    marginTop: -2,
  },
  logoSmoothie: {
    color: "#9bd33e",
    fontSize: 56,
    fontWeight: "800",
    letterSpacing: 0,
    lineHeight: 62,
  },
  logoLeaves: {
    height: 48,
    marginLeft: -10,
    marginTop: -22,
    width: 54,
  },
  logoLeafSmall: {
    left: 2,
    position: "absolute",
    top: 20,
    transform: [{ rotate: "-32deg" }],
  },
  logoLeafLarge: {
    height: 42,
    left: 22,
    position: "absolute",
    top: 2,
    transform: [{ rotate: "40deg" }],
    width: 23,
  },
  heroArt: {
    alignItems: "center",
    height: 475,
    justifyContent: "center",
    maxWidth: 500,
    width: "100%",
  },
  heroImage: {
    height: "200%",
    width: "115%",
  },
  glowCircle: {
    backgroundColor: "#fff8e6",
    borderRadius: 215,
    height: 430,
    opacity: 0.9,
    position: "absolute",
    top: 34,
    width: 430,
  },
  dot: {
    position: "absolute",
  },
  dotOne: {
    left: 18,
    top: 126,
  },
  dotTwo: {
    bottom: 88,
    left: 36,
  },
  dotThree: {
    right: 28,
    top: 310,
  },
  dotFour: {
    right: 56,
    top: 170,
  },
  dotFive: {
    bottom: 130,
    right: 152,
  },
  leaf: {
    backgroundColor: "#7ecb42",
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 2,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 16,
    height: 28,
    width: 18,
  },
  leafOne: {
    left: 126,
    position: "absolute",
    top: 160,
    transform: [{ rotate: "-54deg" }],
  },
  leafTwo: {
    position: "absolute",
    right: 118,
    top: 202,
    transform: [{ rotate: "45deg" }],
  },
  leafThree: {
    bottom: 72,
    position: "absolute",
    right: 132,
    transform: [{ rotate: "62deg" }],
  },
  leafFour: {
    bottom: 106,
    height: 40,
    left: 16,
    position: "absolute",
    transform: [{ rotate: "-28deg" }],
    width: 27,
  },
  blueberry: {
    backgroundColor: "#3f72aa",
    borderRadius: 22,
    height: 44,
    position: "absolute",
    shadowColor: "#1f4067",
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    width: 44,
  },
  blueberryBloom: {
    backgroundColor: "#214c7d",
    borderRadius: 6,
    height: 12,
    left: 16,
    position: "absolute",
    top: 8,
    width: 12,
  },
  blueberryShine: {
    backgroundColor: "#86a8cf",
    borderRadius: 8,
    height: 14,
    left: 7,
    opacity: 0.65,
    position: "absolute",
    top: 8,
    width: 14,
  },
  blueberryOne: {
    left: 72,
    top: 76,
  },
  blueberryTwo: {
    bottom: 72,
    right: 128,
    transform: [{ scale: 0.72 }],
  },
  blueberryThree: {
    bottom: 136,
    left: 78,
    transform: [{ scale: 0.55 }],
  },
  bananaWrap: {
    height: 138,
    left: 28,
    position: "absolute",
    top: 152,
    transform: [{ rotate: "-22deg" }],
    width: 132,
  },
  bananaBack: {
    backgroundColor: "#fff8d4",
    borderRadius: 68,
    height: 94,
    left: 18,
    position: "absolute",
    top: 24,
    width: 112,
  },
  banana: {
    backgroundColor: "#ffd64b",
    borderBottomLeftRadius: 78,
    borderBottomRightRadius: 44,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 54,
    height: 74,
    left: 5,
    position: "absolute",
    top: 30,
    transform: [{ rotate: "16deg" }],
    width: 125,
  },
  bananaStem: {
    backgroundColor: "#9f6427",
    borderRadius: 5,
    height: 28,
    left: 0,
    position: "absolute",
    top: 34,
    transform: [{ rotate: "-2deg" }],
    width: 10,
  },
  bananaTip: {
    backgroundColor: "#7c4c25",
    borderRadius: 6,
    height: 12,
    position: "absolute",
    right: 2,
    top: 88,
    width: 12,
  },
  strawberryWrap: {
    height: 120,
    width: 110,
  },
  strawberryPosition: {
    bottom: 62,
    left: 94,
    position: "absolute",
    transform: [{ rotate: "-12deg" }],
  },
  strawberry: {
    backgroundColor: "#fa4638",
    borderBottomLeftRadius: 52,
    borderBottomRightRadius: 52,
    borderTopLeftRadius: 62,
    borderTopRightRadius: 62,
    height: 105,
    marginTop: 14,
    shadowColor: "#bb261f",
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    width: 94,
  },
  strawberryLeafRow: {
    height: 34,
    left: 36,
    position: "absolute",
    top: 0,
    width: 60,
    zIndex: 2,
  },
  strawberryLeafLeft: {
    height: 29,
    left: 0,
    position: "absolute",
    top: 9,
    transform: [{ rotate: "-72deg" }],
    width: 19,
  },
  strawberryLeafMiddle: {
    height: 35,
    left: 19,
    position: "absolute",
    top: 0,
    transform: [{ rotate: "6deg" }],
    width: 21,
  },
  strawberryLeafRight: {
    height: 29,
    left: 38,
    position: "absolute",
    top: 9,
    transform: [{ rotate: "54deg" }],
    width: 19,
  },
  seed: {
    backgroundColor: "#fd7f61",
    borderRadius: 2,
    height: 6,
    opacity: 0.9,
    position: "absolute",
    width: 3,
  },
  raspberryPosition: {
    position: "absolute",
    right: 44,
    top: 94,
  },
  raspberry: {
    height: 78,
    width: 78,
  },
  raspberryCell: {
    backgroundColor: "#f64262",
    borderColor: "#ff6f84",
    borderRadius: 18,
    borderWidth: 2,
    height: 32,
    position: "absolute",
    shadowColor: "#bf2440",
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 5,
    width: 32,
  },
  kiwiPosition: {
    bottom: 50,
    position: "absolute",
    right: 34,
  },
  kiwiOuter: {
    alignItems: "center",
    backgroundColor: "#95652b",
    borderRadius: 43,
    height: 86,
    justifyContent: "center",
    width: 86,
  },
  kiwiInner: {
    alignItems: "center",
    backgroundColor: "#92d648",
    borderRadius: 37,
    height: 74,
    justifyContent: "center",
    width: 74,
  },
  kiwiCenter: {
    backgroundColor: "#ecfad8",
    borderRadius: 16,
    height: 32,
    width: 32,
  },
  kiwiSeed: {
    backgroundColor: "#24331b",
    borderRadius: 2,
    height: 5,
    position: "absolute",
    width: 3,
  },
  orangePosition: {
    position: "absolute",
    right: 6,
    top: 222,
    transform: [{ rotate: "-18deg" }],
  },
  orangeSlice: {
    backgroundColor: "#ffe9a5",
    borderBottomLeftRadius: 70,
    borderBottomRightRadius: 70,
    height: 70,
    overflow: "hidden",
    padding: 6,
    width: 140,
  },
  orangeFruit: {
    backgroundColor: "#ffb52c",
    borderBottomLeftRadius: 62,
    borderBottomRightRadius: 62,
    flex: 1,
    overflow: "hidden",
  },
  orangeLineOne: {
    backgroundColor: "#ffe58d",
    height: 84,
    left: 62,
    position: "absolute",
    top: -8,
    transform: [{ rotate: "22deg" }],
    width: 3,
  },
  orangeLineTwo: {
    backgroundColor: "#ffe58d",
    height: 84,
    left: 80,
    position: "absolute",
    top: -8,
    transform: [{ rotate: "49deg" }],
    width: 3,
  },
  orangeLineThree: {
    backgroundColor: "#ffe58d",
    height: 84,
    left: 45,
    position: "absolute",
    top: -8,
    transform: [{ rotate: "-20deg" }],
    width: 3,
  },
  cupShadowWrap: {
    alignItems: "center",
    height: 302,
    justifyContent: "flex-start",
    marginTop: 94,
    transform: [{ rotate: "-8deg" }],
    width: 164,
    zIndex: 5,
  },
  lidHandle: {
    borderColor: "#c7d893",
    borderRadius: 46,
    borderWidth: 13,
    height: 88,
    position: "absolute",
    top: 0,
    width: 88,
    zIndex: 1,
  },
  cupLid: {
    backgroundColor: "#eee4b6",
    borderColor: "#f8efcf",
    borderRadius: 34,
    borderWidth: 5,
    height: 54,
    position: "absolute",
    top: 54,
    width: 156,
    zIndex: 4,
  },
  cupBody: {
    backgroundColor: "rgba(255, 238, 201, 0.52)",
    borderColor: "rgba(255, 251, 233, 0.95)",
    borderRadius: 24,
    borderWidth: 5,
    height: 196,
    overflow: "hidden",
    position: "absolute",
    top: 86,
    width: 128,
    zIndex: 2,
  },
  smoothieFill: {
    backgroundColor: "#ff7d78",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    bottom: 0,
    height: 142,
    left: 0,
    opacity: 0.9,
    position: "absolute",
    right: 0,
  },
  cupHighlight: {
    backgroundColor: "rgba(255, 255, 255, 0.42)",
    borderRadius: 12,
    height: 164,
    position: "absolute",
    right: 17,
    top: 16,
    width: 22,
  },
  cupBase: {
    backgroundColor: "#c8d58e",
    borderRadius: 26,
    height: 42,
    position: "absolute",
    top: 262,
    width: 116,
    zIndex: 3,
  },
  cupShadow: {
    backgroundColor: "#dce3b6",
    borderRadius: 58,
    bottom: -28,
    height: 20,
    opacity: 0.6,
    position: "absolute",
    transform: [{ rotate: "8deg" }],
    width: 130,
  },
  footer: {
    alignItems: "center",
    width: "100%",
  },
  welcome: {
    color: "#294832",
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: 0,
    marginBottom: 30,
  },
  button: {
    alignItems: "center",
    backgroundColor: "#9bd33e",
    borderRadius: 36,
    elevation: 6,
    flexDirection: "row",
    height: 74,
    justifyContent: "center",
    maxWidth: 330,
    shadowColor: "#8ac539",
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.26,
    shadowRadius: 18,
    width: "100%",
  },
  buttonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  buttonText: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: 0,
  },
  buttonArrow: {
    color: "#fff",
    fontSize: 42,
    fontWeight: "700",
    lineHeight: 44,
    marginLeft: 18,
    marginTop: -2,
  },
});

export default styles;
